import sys
from itertools import islice

# This program generates xyz files of water for ion parameterization from orca package output file

f = open(sys.argv[1])

for line in f:
    if 'TRAJECTORY STEP' in line:
        # find the coord lines after each sp step
        a = ''.join(islice(f,5,9))

        # split each line 
        b=a.splitlines()

        # find the distance of ion and the binded atom
        b1=b[1].split()

        # convert the distance value from string to float
        c=float(b1[1])

        # round to remove the zeros
        b2=round(c,2)

        # write each line with the binded atom numbers to file 
        g = open(f"Water_Yb2+_0{b2}.txyz", 'w')

        # write the number of atoms and coord lines manually 
        g.write(' 4   # generated by xyzToTxyz, by Hesam A. @ FSU\n')
        g.write('   1 '+b[0]+'   507\n')
        g.write('   2 '+b[1]+'   36  3  4\n')
        g.write('   3 '+b[2]+'   37  2   \n')
        g.write('   4 '+b[3]+'   37  2   \n')
#         g.write(a)
        g.close()
    else:
        pass

