import sys
from itertools import islice

# This program generates xyz files of acetamide for ion parameterization from orca package output file

f = open(sys.argv[1], 'r')

for line in f:
    if 'TRAJECTORY STEP' in line:
        # find the coord lines after each sp step
        a = ''.join(islice(f,5,15))

        # split each line 
        b=a.splitlines()

        # find the distance of ion and the binded atom
        b1=b[1].split()

        # convert the distance value from string to float
        c=float(b1[1])

        # round to remove the zeros
        b2=round(c,2)

        # write each line with the binded atom numbers to file 
        g = open(f"Acetamide_Yb2+_0{b2}.txyz", 'w')

        # write the number of atoms and coord lines manually 
        g.write(' 10  # generated by xyzToTxyz, by Hesam A. @ FSU\n')
        g.write('      1 '+b[0]+'   507  \n')
        g.write('      2 '+b[1]+'   105  4         \n')
        g.write('      3 '+b[2]+'   108  7  4  8  6\n')
        g.write('      4 '+b[3]+'   104  2  3  5   \n')
        g.write('      5 '+b[4]+'   106  4  9 10   \n')
        g.write('      6 '+b[5]+'   109  3         \n')
        g.write('      7 '+b[6]+'   109  3         \n')
        g.write('      8 '+b[7]+'   109  3         \n')
        g.write('      9 '+b[8]+'   107  5         \n')
        g.write('     10 '+b[9]+'   107  5         \n')
        g.close()
    else:
        pass
